// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh49szHTL14A_R02VbHlrI2-h4NDV6bDI',
    appId: '1:664889898588:web:c28f5d5cc765cd725e9899',
    messagingSenderId: '664889898588',
    projectId: 'laniertech2024-d039e',
    authDomain: 'laniertech2024-d039e.firebaseapp.com',
    storageBucket: 'laniertech2024-d039e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfZHtmhyqHYb4l29JdVZbmhDN9PzE0CyQ',
    appId: '1:664889898588:android:e6ffd97ab555520b5e9899',
    messagingSenderId: '664889898588',
    projectId: 'laniertech2024-d039e',
    storageBucket: 'laniertech2024-d039e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXQSlPR1k8iP_TZV3gQPUfPOsat7BtWms',
    appId: '1:664889898588:ios:077d854f395915295e9899',
    messagingSenderId: '664889898588',
    projectId: 'laniertech2024-d039e',
    storageBucket: 'laniertech2024-d039e.appspot.com',
    iosClientId: '664889898588-tedogr1koqqklkhj74up2lo1akeom3r6.apps.googleusercontent.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXQSlPR1k8iP_TZV3gQPUfPOsat7BtWms',
    appId: '1:664889898588:ios:8c3dbbc464f32f955e9899',
    messagingSenderId: '664889898588',
    projectId: 'laniertech2024-d039e',
    storageBucket: 'laniertech2024-d039e.appspot.com',
    iosClientId: '664889898588-jgu2q7j55ghlmj0q42sqm060po5nrbkl.apps.googleusercontent.com',
    iosBundleId: 'com.example.client.RunnerTests',
  );
}
